development:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'development_secret_key_base_change_me') %>

test:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'test_secret_key_base_change_me') %>

production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'production_secret_key_base_change_me') %>
